# Generated by Django 4.2 on 2023-05-25 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('code', models.TextField()),
                ('phone', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_num', models.IntegerField(max_length=16)),
                ('due_date', models.TextField(default=0)),
                ('security_code', models.IntegerField(max_length=10)),
                ('amount_paid', models.FloatField(default=0)),
                ('description', models.CharField(max_length=200)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto_.project')),
            ],
        ),
    ]
