# Generated by Django 4.2.1 on 2023-05-18 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('code', models.TextField()),
                ('phone', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.IntegerField(default=0)),
                ('pay_day', models.DateField(default='2023-05-18')),
                ('amount_paid', models.FloatField(default=0)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto_.project')),
            ],
        ),
    ]
