# Generated by Django 4.2 on 2023-05-19 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_', '0002_pay_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='user',
        ),
    ]
